name: Linting and unit tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Use Python version 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    # - name: Update pip
    #   run: |
    #     python -m pip install --upgrade pip
    # - name: Install requirements
    #   run: |
    #     python -m pip install -r requirements.txt
    # - name: Install Pytest
    #   run: |
    #     python -m pip install pytest
    # - name: Run unit tests
    #   run: | 
    #     pytest --ignore F841 tests
    # - name: Run linting
    #   run: | 
    #     flake8 src/model/
