name: Train and list models

on:
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'Resource group name'
        required: true
        default: 'rg-dev-mlops' 
        type: string
      aml_workspace:
        description: 'Azure Machine Learning workspace name'
        required: true
        default: 'mlw-dev-mlops' 
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
        name: development
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Set Azure ML workspace as default
      run: |
        az configure --defaults group="${{ github.event.inputs.resource_group }}"
        az configure --defaults workspace="${{ github.event.inputs.aml_workspace }}"
    - name: Deploy model
      run: |
        cd src
        export ENDPOINT_NAME="diabetes-endpoint"
        az ml online-endpoint create --name $ENDPOINT_NAME -f endpoint.yaml
        JOB_NAME=$(az ml job list --query "[0].name" | tr -d '"')

        az ml model create --name "diabetes-model" \
                   --type "mlflow_model" \
                   --path "azureml://jobs/$JOB_NAME/outputs/artifacts/model"

        az ml online-deployment create --name diabetes-deployment --endpoint $ENDPOINT_NAME -f deployment.yaml --all-traffic